### ISSUE TITLE
How to use this code ?

### ISSUE THREAD

**Issue by Laihu08** [BerensRWU/DenseMap#1]
There is not input file path, where should I run this code? please help me out to do this, since this is my first time. Thanks a lot !

**Comment by BerensRWU** [comment]
In main.py row 56 you can change the root path, where you have stored the data. Please note that the script is written for datasets that are in the KITTI format. For other datasets you have to change main.py.

**Comment by Laihu08** [comment]
> In main.py row 56 you can change the root path, where you have stored the data. Please note that the script is written for datasets that are in the KITTI format. For other datasets you have to change main.py.

Thanks a lot, I didn't see that.
