### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Laihu08** [BerensRWU/DenseMap#2]
![Screenshot from 2021-02-17 10-55-54](https://user-images.githubusercontent.com/55731288/108149941-c0058480-710e-11eb-961b-686b1728c283.png)
It showing some syntax error, can you please help me to solve this error ? and how can i visualize the output ?

**Comment by Laihu08** [comment]
> ![Screenshot from 2021-02-17 10-55-54](https://user-images.githubusercontent.com/55731288/108149941-c0058480-710e-11eb-961b-686b1728c283.png)
> It showing some syntax error, can you please help me to solve this error ? and how can i visualize the output ?
hey hi, I think i solved the error. by just adding % in line 77 like this plt.imsave("depth_map_%06d.png" % cur_id,out)
Thanks a lot for your time, this code really helped me to learn deeper about this.

**Comment by BerensRWU** [comment]
Thank you for your feedback.
There was a comma missing.
