### ISSUE TITLE
 To convert dense depth map to point cloud 

### ISSUE THREAD

**Issue by Laihu08** [BerensRWU/DenseMap#3]
Hi, I saw your impressive work and am curious, is it possible to project back the estimated dense depth map to point cloud coordinates? if so, can you please provide a code for that? Thanks in advance.

**Comment by BerensRWU** [comment]
I did not implement it, but here is a description how to get a point cloud from the depth map: [https://medium.com/yodayoda/from-depth-map-to-point-cloud-7473721d3f](https://medium.com/yodayoda/from-depth-map-to-point-cloud-7473721d3f)

**Comment by BerensRWU** [comment]
I have added a code that generates a point cloud from a depth map. Reference code is from here: https://github.com/MankaranSingh/Auto-Depth/tree/master/inverse_projection
