### ISSUE TITLE
Some questions about the code 

### ISSUE THREAD

**Issue by heng94** [BerensRWU/DenseMap#5]
Hi, thanks for sharing the code.
I have some problems with the code in _**depth_map.py**_. 
To deal with images in sequence 04 where the size is 370 * 1226, 
the error is located in line 10:
_mX[np.int32(Pts[1]),np.int32(Pts[0])] = Pts[0] - np.round(Pts[0])_
_IndexError: index 370 is out of bounds for axis 0 with size 370_

I found that the value of Pts[1] is larger than 370 and the value of Pts[0] is larger than 1226, so there is an index error.
The calib.txt is correct because sequences 00,01,02,03 can be done well. 
Can you give some suggestions? Thanks very much.

**Comment by immaturehaan** [comment]
hello @heng94, did you fix this error? thank you so much.

**Comment by BerensRWU** [comment]
The problem was that in the function _rect2Img_ the height and width of the image was hard coded.
In the updated version _rect2Img_ takes the height and width of the image as input. This should solve the issue.
